name: drawing_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  dxf: ^3.1.3
  provider: ^6.1.2
  auto_size_text: ^3.0.0
  flutter_speed_dial: ^7.0.0
  flutter_email_sender: ^6.0.3
  path: ^1.9.0
  path_provider: ^2.1.3
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
